### ISSUE TITLE
search in Zotero API no longer working

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-oebl-research-tool-front-end#30]
Search in the Zotero API is no longer working. The request is using undefined as a user. Seems as the user set in the .env_production is not working correctly.

Thats the log from the pod showing the false request to the zotero API:

```
(node:26) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://api.zotero.org/users/undefined/items?q=te reason: Unexpected token I in JSON at position 0
    at /workspace/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by sennierer** [comment]
changed due date to March 11, 2022

**Comment by sennierer** [comment]
In GitLab by @PhilipRoeggla on Mar 7, 2022, 14:32

created branch [`30-search-in-zotero-api-no-longer-working`](/acdh-oeaw/oebl/oebl-research-tool-front-end/-/compare/master...30-search-in-zotero-api-no-longer-working) to address this issue

**Comment by sennierer** [comment]
resolved by moving the env variable to Gitlab

**Comment by sennierer** [comment]
In GitLab by @PhilipRoeggla on Mar 7, 2022, 14:37

mentioned in commit 350fb93044b440a8c1f0ff5f04e4f60e888b1b9a
